import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

// IMPORTANT: the service worker generated by this plugin only ever caches
// static build assets (JS/CSS/HTML/icons) — it has no knowledge of and never
// touches IndexedDB. Your encrypted vault data is never written into a
// service-worker cache. We deliberately do NOT add any runtimeCaching rules
// here, because there is no backend to call and we don't want to
// accidentally introduce a rule that could cache something sensitive later.
export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['icons/icon-192.png', 'icons/icon-512.png'],
      manifest: {
        name: 'Local Budget',
        short_name: 'Budget',
        description: 'A private, local-first personal budgeting app. Your data never leaves this device unless you export it.',
        theme_color: '#F7F6F2',
        background_color: '#F7F6F2',
        display: 'standalone',
        start_url: '/',
        icons: [
          { src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png' },
          { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png' },
          { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' }
        ]
      },
      workbox: {
        // Precache the app shell only. No runtime caching rules — see note above.
        globPatterns: ['**/*.{js,css,html,svg,png,ico}']
      }
    })
  ]
});
